# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3e409f432662f1e702d410a99e450f9db77ee3fa1e1d783cbea3a6c9c37edd9413064ba28f38d62815d0cd65b41d406ba9786af34379a6ac15f1d12587b4620

test:
  secret_key_base: e87300e89eb858b5671356b4c740b67d44e81ac274c9a0ab7502018c8300c402ed89238757e6435bd1f0932bc983a81204a385bf1e631be48a2fcfb0c17002e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
